# Generated by Django 2.1.5 on 2019-02-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=30)),
                ('roolno', models.IntegerField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
            ],
        ),
    ]
