# Generated by Django 2.1.5 on 2019-02-08 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Employee',
        ),
    ]
