# Generated by Django 2.1.5 on 2019-02-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdas', '0002_auto_20190207_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('no', models.IntegerField()),
                ('salary', models.FloatField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='roolno',
            field=models.IntegerField(),
        ),
    ]
